name: phpers-summit-2022-first-day-commit

services:
  php:
    build:
      target: php
      context: .
    volumes:
      - .:/app
      - ~/.composer:/var/.composer
      - .docker/php/development.ini:/usr/local/etc/php/conf.d/zz-php.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: 'serverName=phpers.srv'
    depends_on:
      - db

  web:
    image: nginx:1.21-alpine
    volumes:
      - ./public:/app/public
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:14-alpine3.14
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: phpers
      POSTGRES_PASSWORD: phpers
      POSTGRES_DB: phpers
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  db: ~
