version: '3.9'

services:
  php:
    build:
      target: php
      context: .
    volumes:
      - .:/app
      - ~/.composer:/var/.composer
      - .docker/php/development.ini:/usr/local/erc/php/conf.d/zz-php.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: 'serverName=phpers.srv'

  web:
    image: nginx:1.21-alpine
    volumes:
      - ./public:/app/public
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
