services:
  _defaults:
    autowire: true
    autoconfigure: true

  Displate\Phpers\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  Displate\Phpers\Presentation\Http\:
    resource: '%kernel.project_dir%/src/Presentation/Http/'
    tags: [ 'controller.service_arguments' ]

  Displate\Phpers\Infrastructure\Poster\ExternalServiceRepository:
    public: true
